CREATE TABLE worker(
id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
name VARCHAR(1000) NOT NULL CHECK(LENGTH(name)>=2 AND LENGTH(name)<=1000),
birthday DATE CHECK (birthday>'1900-12-31'),
salary INT CHECK (salary>=100 AND salary<=100000),
levels VARCHAR NOT NULL CHECK (levels IN ('TRAINEE', 'JUNIOR', 'MIDDLE', 'SENIOR'))
);

CREATE TABLE client(
id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
name VARCHAR(1000) NOT NULL CHECK(LENGTH(name)>=2 AND LENGTH(name)<=1000)
);

CREATE TABLE project(
id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
client_id BIGINT NOT NULL,
start_date DATE NOT NULL,
finish_date DATE NOT NULL,
CONSTRAINT project_client_fk FOREIGN KEY (client_id) REFERENCES client (id)
);

CREATE TABLE project_worker(
id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
project_id BIGINT NOT NULL,
worker_id BIGINT NOT NULL
);